name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.Azure_Credentials }}
        
      - name: Deploy Resource Group rg-githubactons
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionID: 7c1ae066-36c2-4723-8172-caf805c36c16
          region: Canada Central
          template: ./arm-templates/resourcegroup.json
          parameters:
            location="East US"
            resourceGroupName=rg-githubactions
          deploymentName: rg-githubactions

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          subscriptionID: 7c1ae066-36c2-4723-8172-caf805c36c16
          template: ./arm-templates/storageaccount.json
          parameters: 
            sku=Standard_LRS
            storageAccountName=globostg003
            location="Canada Central"
          deploymentMode: incremental

      - run: echo ${{ steps.storageAccountDeploy.outputs.BlobUri }}